/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authAuthCallbackRouteImport } from './routes/(auth)/auth-callback'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants/index'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties/index'
import { Route as AuthenticatedMetersIndexRouteImport } from './routes/_authenticated/meters/index'
import { Route as AuthenticatedLandlordsIndexRouteImport } from './routes/_authenticated/landlords/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedBankAccountsIndexRouteImport } from './routes/_authenticated/bank-accounts/index'
import { Route as AuthenticatedTenantsNewRouteImport } from './routes/_authenticated/tenants/new'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates/new'
import { Route as AuthenticatedTemplatesIdRouteImport } from './routes/_authenticated/templates/$id'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedSettingsStaffRouteImport } from './routes/_authenticated/settings/staff'
import { Route as AuthenticatedSettingsInvoiceDocsRouteImport } from './routes/_authenticated/settings/invoice-docs'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedReportsOutstandingRouteImport } from './routes/_authenticated/reports/outstanding'
import { Route as AuthenticatedReportsMonthlyRouteImport } from './routes/_authenticated/reports/monthly'
import { Route as AuthenticatedReportsFollowUpRouteImport } from './routes/_authenticated/reports/follow-up'
import { Route as AuthenticatedReportsAgingRouteImport } from './routes/_authenticated/reports/aging'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties/new'
import { Route as AuthenticatedMetersNewRouteImport } from './routes/_authenticated/meters/new'
import { Route as AuthenticatedLandlordsNewRouteImport } from './routes/_authenticated/landlords/new'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedContractsRenewalsRouteImport } from './routes/_authenticated/contracts/renewals'
import { Route as AuthenticatedContractsNewRouteImport } from './routes/_authenticated/contracts/new'
import { Route as AuthenticatedBankAccountsNewRouteImport } from './routes/_authenticated/bank-accounts/new'
import { Route as AuthenticatedTenantsIdIndexRouteImport } from './routes/_authenticated/tenants/$id/index'
import { Route as AuthenticatedPropertiesIdIndexRouteImport } from './routes/_authenticated/properties/$id/index'
import { Route as AuthenticatedMetersIdIndexRouteImport } from './routes/_authenticated/meters/$id/index'
import { Route as AuthenticatedLandlordsIdIndexRouteImport } from './routes/_authenticated/landlords/$id/index'
import { Route as AuthenticatedInvoicesIdIndexRouteImport } from './routes/_authenticated/invoices/$id/index'
import { Route as AuthenticatedContractsIdIndexRouteImport } from './routes/_authenticated/contracts/$id/index'
import { Route as AuthenticatedBankAccountsIdIndexRouteImport } from './routes/_authenticated/bank-accounts/$id/index'
import { Route as AuthenticatedInvoicesIdReceiptRouteImport } from './routes/_authenticated/invoices/$id/receipt'
import { Route as AuthenticatedInvoicesIdPrintRouteImport } from './routes/_authenticated/invoices/$id/print'
import { Route as AuthenticatedContractsIdPrintRouteImport } from './routes/_authenticated/contracts/$id/print'
import { Route as AuthenticatedContractsIdDepositReturnRouteImport } from './routes/_authenticated/contracts/$id/deposit-return'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthCallbackRoute = authAuthCallbackRouteImport.update({
  id: '/(auth)/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetersIndexRoute =
  AuthenticatedMetersIndexRouteImport.update({
    id: '/meters/',
    path: '/meters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandlordsIndexRoute =
  AuthenticatedLandlordsIndexRouteImport.update({
    id: '/landlords/',
    path: '/landlords/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankAccountsIndexRoute =
  AuthenticatedBankAccountsIndexRouteImport.update({
    id: '/bank-accounts/',
    path: '/bank-accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantsNewRoute = AuthenticatedTenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIdRoute =
  AuthenticatedTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsStaffRoute =
  AuthenticatedSettingsStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsInvoiceDocsRoute =
  AuthenticatedSettingsInvoiceDocsRouteImport.update({
    id: '/invoice-docs',
    path: '/invoice-docs',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsOutstandingRoute =
  AuthenticatedReportsOutstandingRouteImport.update({
    id: '/reports/outstanding',
    path: '/reports/outstanding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsMonthlyRoute =
  AuthenticatedReportsMonthlyRouteImport.update({
    id: '/reports/monthly',
    path: '/reports/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsFollowUpRoute =
  AuthenticatedReportsFollowUpRouteImport.update({
    id: '/reports/follow-up',
    path: '/reports/follow-up',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAgingRoute =
  AuthenticatedReportsAgingRouteImport.update({
    id: '/reports/aging',
    path: '/reports/aging',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetersNewRoute = AuthenticatedMetersNewRouteImport.update({
  id: '/meters/new',
  path: '/meters/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLandlordsNewRoute =
  AuthenticatedLandlordsNewRouteImport.update({
    id: '/landlords/new',
    path: '/landlords/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRenewalsRoute =
  AuthenticatedContractsRenewalsRouteImport.update({
    id: '/contracts/renewals',
    path: '/contracts/renewals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsNewRoute =
  AuthenticatedContractsNewRouteImport.update({
    id: '/contracts/new',
    path: '/contracts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankAccountsNewRoute =
  AuthenticatedBankAccountsNewRouteImport.update({
    id: '/bank-accounts/new',
    path: '/bank-accounts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantsIdIndexRoute =
  AuthenticatedTenantsIdIndexRouteImport.update({
    id: '/tenants/$id/',
    path: '/tenants/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIdIndexRoute =
  AuthenticatedPropertiesIdIndexRouteImport.update({
    id: '/properties/$id/',
    path: '/properties/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetersIdIndexRoute =
  AuthenticatedMetersIdIndexRouteImport.update({
    id: '/meters/$id/',
    path: '/meters/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandlordsIdIndexRoute =
  AuthenticatedLandlordsIdIndexRouteImport.update({
    id: '/landlords/$id/',
    path: '/landlords/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdIndexRoute =
  AuthenticatedInvoicesIdIndexRouteImport.update({
    id: '/invoices/$id/',
    path: '/invoices/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIdIndexRoute =
  AuthenticatedContractsIdIndexRouteImport.update({
    id: '/contracts/$id/',
    path: '/contracts/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankAccountsIdIndexRoute =
  AuthenticatedBankAccountsIdIndexRouteImport.update({
    id: '/bank-accounts/$id/',
    path: '/bank-accounts/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdReceiptRoute =
  AuthenticatedInvoicesIdReceiptRouteImport.update({
    id: '/invoices/$id/receipt',
    path: '/invoices/$id/receipt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdPrintRoute =
  AuthenticatedInvoicesIdPrintRouteImport.update({
    id: '/invoices/$id/print',
    path: '/invoices/$id/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIdPrintRoute =
  AuthenticatedContractsIdPrintRouteImport.update({
    id: '/contracts/$id/print',
    path: '/contracts/$id/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIdDepositReturnRoute =
  AuthenticatedContractsIdDepositReturnRouteImport.update({
    id: '/contracts/$id/deposit-return',
    path: '/contracts/$id/deposit-return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/auth-callback': typeof authAuthCallbackRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/bank-accounts/new': typeof AuthenticatedBankAccountsNewRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/contracts/renewals': typeof AuthenticatedContractsRenewalsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/landlords/new': typeof AuthenticatedLandlordsNewRoute
  '/meters/new': typeof AuthenticatedMetersNewRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/reports/aging': typeof AuthenticatedReportsAgingRoute
  '/reports/follow-up': typeof AuthenticatedReportsFollowUpRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/reports/outstanding': typeof AuthenticatedReportsOutstandingRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/invoice-docs': typeof AuthenticatedSettingsInvoiceDocsRoute
  '/settings/staff': typeof AuthenticatedSettingsStaffRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/bank-accounts/': typeof AuthenticatedBankAccountsIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/landlords/': typeof AuthenticatedLandlordsIndexRoute
  '/meters/': typeof AuthenticatedMetersIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/contracts/$id/deposit-return': typeof AuthenticatedContractsIdDepositReturnRoute
  '/contracts/$id/print': typeof AuthenticatedContractsIdPrintRoute
  '/invoices/$id/print': typeof AuthenticatedInvoicesIdPrintRoute
  '/invoices/$id/receipt': typeof AuthenticatedInvoicesIdReceiptRoute
  '/bank-accounts/$id/': typeof AuthenticatedBankAccountsIdIndexRoute
  '/contracts/$id/': typeof AuthenticatedContractsIdIndexRoute
  '/invoices/$id/': typeof AuthenticatedInvoicesIdIndexRoute
  '/landlords/$id/': typeof AuthenticatedLandlordsIdIndexRoute
  '/meters/$id/': typeof AuthenticatedMetersIdIndexRoute
  '/properties/$id/': typeof AuthenticatedPropertiesIdIndexRoute
  '/tenants/$id/': typeof AuthenticatedTenantsIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth-callback': typeof authAuthCallbackRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/bank-accounts/new': typeof AuthenticatedBankAccountsNewRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/contracts/renewals': typeof AuthenticatedContractsRenewalsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/landlords/new': typeof AuthenticatedLandlordsNewRoute
  '/meters/new': typeof AuthenticatedMetersNewRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/reports/aging': typeof AuthenticatedReportsAgingRoute
  '/reports/follow-up': typeof AuthenticatedReportsFollowUpRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/reports/outstanding': typeof AuthenticatedReportsOutstandingRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/invoice-docs': typeof AuthenticatedSettingsInvoiceDocsRoute
  '/settings/staff': typeof AuthenticatedSettingsStaffRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/bank-accounts': typeof AuthenticatedBankAccountsIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/landlords': typeof AuthenticatedLandlordsIndexRoute
  '/meters': typeof AuthenticatedMetersIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/contracts/$id/deposit-return': typeof AuthenticatedContractsIdDepositReturnRoute
  '/contracts/$id/print': typeof AuthenticatedContractsIdPrintRoute
  '/invoices/$id/print': typeof AuthenticatedInvoicesIdPrintRoute
  '/invoices/$id/receipt': typeof AuthenticatedInvoicesIdReceiptRoute
  '/bank-accounts/$id': typeof AuthenticatedBankAccountsIdIndexRoute
  '/contracts/$id': typeof AuthenticatedContractsIdIndexRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdIndexRoute
  '/landlords/$id': typeof AuthenticatedLandlordsIdIndexRoute
  '/meters/$id': typeof AuthenticatedMetersIdIndexRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdIndexRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/auth-callback': typeof authAuthCallbackRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bank-accounts/new': typeof AuthenticatedBankAccountsNewRoute
  '/_authenticated/contracts/new': typeof AuthenticatedContractsNewRoute
  '/_authenticated/contracts/renewals': typeof AuthenticatedContractsRenewalsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/landlords/new': typeof AuthenticatedLandlordsNewRoute
  '/_authenticated/meters/new': typeof AuthenticatedMetersNewRoute
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/reports/aging': typeof AuthenticatedReportsAgingRoute
  '/_authenticated/reports/follow-up': typeof AuthenticatedReportsFollowUpRoute
  '/_authenticated/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/_authenticated/reports/outstanding': typeof AuthenticatedReportsOutstandingRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/invoice-docs': typeof AuthenticatedSettingsInvoiceDocsRoute
  '/_authenticated/settings/staff': typeof AuthenticatedSettingsStaffRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/_authenticated/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/_authenticated/bank-accounts/': typeof AuthenticatedBankAccountsIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/landlords/': typeof AuthenticatedLandlordsIndexRoute
  '/_authenticated/meters/': typeof AuthenticatedMetersIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/contracts/$id/deposit-return': typeof AuthenticatedContractsIdDepositReturnRoute
  '/_authenticated/contracts/$id/print': typeof AuthenticatedContractsIdPrintRoute
  '/_authenticated/invoices/$id/print': typeof AuthenticatedInvoicesIdPrintRoute
  '/_authenticated/invoices/$id/receipt': typeof AuthenticatedInvoicesIdReceiptRoute
  '/_authenticated/bank-accounts/$id/': typeof AuthenticatedBankAccountsIdIndexRoute
  '/_authenticated/contracts/$id/': typeof AuthenticatedContractsIdIndexRoute
  '/_authenticated/invoices/$id/': typeof AuthenticatedInvoicesIdIndexRoute
  '/_authenticated/landlords/$id/': typeof AuthenticatedLandlordsIdIndexRoute
  '/_authenticated/meters/$id/': typeof AuthenticatedMetersIdIndexRoute
  '/_authenticated/properties/$id/': typeof AuthenticatedPropertiesIdIndexRoute
  '/_authenticated/tenants/$id/': typeof AuthenticatedTenantsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth-callback'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/activity-log'
    | '/dashboard'
    | '/bank-accounts/new'
    | '/contracts/new'
    | '/contracts/renewals'
    | '/errors/$error'
    | '/invoices/new'
    | '/landlords/new'
    | '/meters/new'
    | '/properties/new'
    | '/reports/aging'
    | '/reports/follow-up'
    | '/reports/monthly'
    | '/reports/outstanding'
    | '/settings/appearance'
    | '/settings/invoice-docs'
    | '/settings/staff'
    | '/settings/system'
    | '/templates/$id'
    | '/templates/new'
    | '/tenants/new'
    | '/bank-accounts/'
    | '/contracts/'
    | '/invoices/'
    | '/landlords/'
    | '/meters/'
    | '/properties/'
    | '/settings/'
    | '/templates/'
    | '/tenants/'
    | '/contracts/$id/deposit-return'
    | '/contracts/$id/print'
    | '/invoices/$id/print'
    | '/invoices/$id/receipt'
    | '/bank-accounts/$id/'
    | '/contracts/$id/'
    | '/invoices/$id/'
    | '/landlords/$id/'
    | '/meters/$id/'
    | '/properties/$id/'
    | '/tenants/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-callback'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/activity-log'
    | '/dashboard'
    | '/'
    | '/bank-accounts/new'
    | '/contracts/new'
    | '/contracts/renewals'
    | '/errors/$error'
    | '/invoices/new'
    | '/landlords/new'
    | '/meters/new'
    | '/properties/new'
    | '/reports/aging'
    | '/reports/follow-up'
    | '/reports/monthly'
    | '/reports/outstanding'
    | '/settings/appearance'
    | '/settings/invoice-docs'
    | '/settings/staff'
    | '/settings/system'
    | '/templates/$id'
    | '/templates/new'
    | '/tenants/new'
    | '/bank-accounts'
    | '/contracts'
    | '/invoices'
    | '/landlords'
    | '/meters'
    | '/properties'
    | '/settings'
    | '/templates'
    | '/tenants'
    | '/contracts/$id/deposit-return'
    | '/contracts/$id/print'
    | '/invoices/$id/print'
    | '/invoices/$id/receipt'
    | '/bank-accounts/$id'
    | '/contracts/$id'
    | '/invoices/$id'
    | '/landlords/$id'
    | '/meters/$id'
    | '/properties/$id'
    | '/tenants/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/auth-callback'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/activity-log'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/bank-accounts/new'
    | '/_authenticated/contracts/new'
    | '/_authenticated/contracts/renewals'
    | '/_authenticated/errors/$error'
    | '/_authenticated/invoices/new'
    | '/_authenticated/landlords/new'
    | '/_authenticated/meters/new'
    | '/_authenticated/properties/new'
    | '/_authenticated/reports/aging'
    | '/_authenticated/reports/follow-up'
    | '/_authenticated/reports/monthly'
    | '/_authenticated/reports/outstanding'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/invoice-docs'
    | '/_authenticated/settings/staff'
    | '/_authenticated/settings/system'
    | '/_authenticated/templates/$id'
    | '/_authenticated/templates/new'
    | '/_authenticated/tenants/new'
    | '/_authenticated/bank-accounts/'
    | '/_authenticated/contracts/'
    | '/_authenticated/invoices/'
    | '/_authenticated/landlords/'
    | '/_authenticated/meters/'
    | '/_authenticated/properties/'
    | '/_authenticated/settings/'
    | '/_authenticated/templates/'
    | '/_authenticated/tenants/'
    | '/_authenticated/contracts/$id/deposit-return'
    | '/_authenticated/contracts/$id/print'
    | '/_authenticated/invoices/$id/print'
    | '/_authenticated/invoices/$id/receipt'
    | '/_authenticated/bank-accounts/$id/'
    | '/_authenticated/contracts/$id/'
    | '/_authenticated/invoices/$id/'
    | '/_authenticated/landlords/$id/'
    | '/_authenticated/meters/$id/'
    | '/_authenticated/properties/$id/'
    | '/_authenticated/tenants/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authAuthCallbackRoute: typeof authAuthCallbackRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth-callback': {
      id: '/(auth)/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof authAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meters/': {
      id: '/_authenticated/meters/'
      path: '/meters'
      fullPath: '/meters/'
      preLoaderRoute: typeof AuthenticatedMetersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landlords/': {
      id: '/_authenticated/landlords/'
      path: '/landlords'
      fullPath: '/landlords/'
      preLoaderRoute: typeof AuthenticatedLandlordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank-accounts/': {
      id: '/_authenticated/bank-accounts/'
      path: '/bank-accounts'
      fullPath: '/bank-accounts/'
      preLoaderRoute: typeof AuthenticatedBankAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/new': {
      id: '/_authenticated/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof AuthenticatedTenantsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$id': {
      id: '/_authenticated/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AuthenticatedTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/staff': {
      id: '/_authenticated/settings/staff'
      path: '/staff'
      fullPath: '/settings/staff'
      preLoaderRoute: typeof AuthenticatedSettingsStaffRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/invoice-docs': {
      id: '/_authenticated/settings/invoice-docs'
      path: '/invoice-docs'
      fullPath: '/settings/invoice-docs'
      preLoaderRoute: typeof AuthenticatedSettingsInvoiceDocsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/outstanding': {
      id: '/_authenticated/reports/outstanding'
      path: '/reports/outstanding'
      fullPath: '/reports/outstanding'
      preLoaderRoute: typeof AuthenticatedReportsOutstandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/monthly': {
      id: '/_authenticated/reports/monthly'
      path: '/reports/monthly'
      fullPath: '/reports/monthly'
      preLoaderRoute: typeof AuthenticatedReportsMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/follow-up': {
      id: '/_authenticated/reports/follow-up'
      path: '/reports/follow-up'
      fullPath: '/reports/follow-up'
      preLoaderRoute: typeof AuthenticatedReportsFollowUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/aging': {
      id: '/_authenticated/reports/aging'
      path: '/reports/aging'
      fullPath: '/reports/aging'
      preLoaderRoute: typeof AuthenticatedReportsAgingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meters/new': {
      id: '/_authenticated/meters/new'
      path: '/meters/new'
      fullPath: '/meters/new'
      preLoaderRoute: typeof AuthenticatedMetersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landlords/new': {
      id: '/_authenticated/landlords/new'
      path: '/landlords/new'
      fullPath: '/landlords/new'
      preLoaderRoute: typeof AuthenticatedLandlordsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/renewals': {
      id: '/_authenticated/contracts/renewals'
      path: '/contracts/renewals'
      fullPath: '/contracts/renewals'
      preLoaderRoute: typeof AuthenticatedContractsRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/new': {
      id: '/_authenticated/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof AuthenticatedContractsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank-accounts/new': {
      id: '/_authenticated/bank-accounts/new'
      path: '/bank-accounts/new'
      fullPath: '/bank-accounts/new'
      preLoaderRoute: typeof AuthenticatedBankAccountsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/$id/': {
      id: '/_authenticated/tenants/$id/'
      path: '/tenants/$id'
      fullPath: '/tenants/$id/'
      preLoaderRoute: typeof AuthenticatedTenantsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$id/': {
      id: '/_authenticated/properties/$id/'
      path: '/properties/$id'
      fullPath: '/properties/$id/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meters/$id/': {
      id: '/_authenticated/meters/$id/'
      path: '/meters/$id'
      fullPath: '/meters/$id/'
      preLoaderRoute: typeof AuthenticatedMetersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landlords/$id/': {
      id: '/_authenticated/landlords/$id/'
      path: '/landlords/$id'
      fullPath: '/landlords/$id/'
      preLoaderRoute: typeof AuthenticatedLandlordsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id/': {
      id: '/_authenticated/invoices/$id/'
      path: '/invoices/$id'
      fullPath: '/invoices/$id/'
      preLoaderRoute: typeof AuthenticatedInvoicesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$id/': {
      id: '/_authenticated/contracts/$id/'
      path: '/contracts/$id'
      fullPath: '/contracts/$id/'
      preLoaderRoute: typeof AuthenticatedContractsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank-accounts/$id/': {
      id: '/_authenticated/bank-accounts/$id/'
      path: '/bank-accounts/$id'
      fullPath: '/bank-accounts/$id/'
      preLoaderRoute: typeof AuthenticatedBankAccountsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id/receipt': {
      id: '/_authenticated/invoices/$id/receipt'
      path: '/invoices/$id/receipt'
      fullPath: '/invoices/$id/receipt'
      preLoaderRoute: typeof AuthenticatedInvoicesIdReceiptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id/print': {
      id: '/_authenticated/invoices/$id/print'
      path: '/invoices/$id/print'
      fullPath: '/invoices/$id/print'
      preLoaderRoute: typeof AuthenticatedInvoicesIdPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$id/print': {
      id: '/_authenticated/contracts/$id/print'
      path: '/contracts/$id/print'
      fullPath: '/contracts/$id/print'
      preLoaderRoute: typeof AuthenticatedContractsIdPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$id/deposit-return': {
      id: '/_authenticated/contracts/$id/deposit-return'
      path: '/contracts/$id/deposit-return'
      fullPath: '/contracts/$id/deposit-return'
      preLoaderRoute: typeof AuthenticatedContractsIdDepositReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsInvoiceDocsRoute: typeof AuthenticatedSettingsInvoiceDocsRoute
  AuthenticatedSettingsStaffRoute: typeof AuthenticatedSettingsStaffRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsInvoiceDocsRoute: AuthenticatedSettingsInvoiceDocsRoute,
    AuthenticatedSettingsStaffRoute: AuthenticatedSettingsStaffRoute,
    AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBankAccountsNewRoute: typeof AuthenticatedBankAccountsNewRoute
  AuthenticatedContractsNewRoute: typeof AuthenticatedContractsNewRoute
  AuthenticatedContractsRenewalsRoute: typeof AuthenticatedContractsRenewalsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedLandlordsNewRoute: typeof AuthenticatedLandlordsNewRoute
  AuthenticatedMetersNewRoute: typeof AuthenticatedMetersNewRoute
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedReportsAgingRoute: typeof AuthenticatedReportsAgingRoute
  AuthenticatedReportsFollowUpRoute: typeof AuthenticatedReportsFollowUpRoute
  AuthenticatedReportsMonthlyRoute: typeof AuthenticatedReportsMonthlyRoute
  AuthenticatedReportsOutstandingRoute: typeof AuthenticatedReportsOutstandingRoute
  AuthenticatedTemplatesIdRoute: typeof AuthenticatedTemplatesIdRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedTenantsNewRoute: typeof AuthenticatedTenantsNewRoute
  AuthenticatedBankAccountsIndexRoute: typeof AuthenticatedBankAccountsIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedLandlordsIndexRoute: typeof AuthenticatedLandlordsIndexRoute
  AuthenticatedMetersIndexRoute: typeof AuthenticatedMetersIndexRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
  AuthenticatedContractsIdDepositReturnRoute: typeof AuthenticatedContractsIdDepositReturnRoute
  AuthenticatedContractsIdPrintRoute: typeof AuthenticatedContractsIdPrintRoute
  AuthenticatedInvoicesIdPrintRoute: typeof AuthenticatedInvoicesIdPrintRoute
  AuthenticatedInvoicesIdReceiptRoute: typeof AuthenticatedInvoicesIdReceiptRoute
  AuthenticatedBankAccountsIdIndexRoute: typeof AuthenticatedBankAccountsIdIndexRoute
  AuthenticatedContractsIdIndexRoute: typeof AuthenticatedContractsIdIndexRoute
  AuthenticatedInvoicesIdIndexRoute: typeof AuthenticatedInvoicesIdIndexRoute
  AuthenticatedLandlordsIdIndexRoute: typeof AuthenticatedLandlordsIdIndexRoute
  AuthenticatedMetersIdIndexRoute: typeof AuthenticatedMetersIdIndexRoute
  AuthenticatedPropertiesIdIndexRoute: typeof AuthenticatedPropertiesIdIndexRoute
  AuthenticatedTenantsIdIndexRoute: typeof AuthenticatedTenantsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBankAccountsNewRoute: AuthenticatedBankAccountsNewRoute,
  AuthenticatedContractsNewRoute: AuthenticatedContractsNewRoute,
  AuthenticatedContractsRenewalsRoute: AuthenticatedContractsRenewalsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedLandlordsNewRoute: AuthenticatedLandlordsNewRoute,
  AuthenticatedMetersNewRoute: AuthenticatedMetersNewRoute,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedReportsAgingRoute: AuthenticatedReportsAgingRoute,
  AuthenticatedReportsFollowUpRoute: AuthenticatedReportsFollowUpRoute,
  AuthenticatedReportsMonthlyRoute: AuthenticatedReportsMonthlyRoute,
  AuthenticatedReportsOutstandingRoute: AuthenticatedReportsOutstandingRoute,
  AuthenticatedTemplatesIdRoute: AuthenticatedTemplatesIdRoute,
  AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
  AuthenticatedTenantsNewRoute: AuthenticatedTenantsNewRoute,
  AuthenticatedBankAccountsIndexRoute: AuthenticatedBankAccountsIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedLandlordsIndexRoute: AuthenticatedLandlordsIndexRoute,
  AuthenticatedMetersIndexRoute: AuthenticatedMetersIndexRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
  AuthenticatedContractsIdDepositReturnRoute:
    AuthenticatedContractsIdDepositReturnRoute,
  AuthenticatedContractsIdPrintRoute: AuthenticatedContractsIdPrintRoute,
  AuthenticatedInvoicesIdPrintRoute: AuthenticatedInvoicesIdPrintRoute,
  AuthenticatedInvoicesIdReceiptRoute: AuthenticatedInvoicesIdReceiptRoute,
  AuthenticatedBankAccountsIdIndexRoute: AuthenticatedBankAccountsIdIndexRoute,
  AuthenticatedContractsIdIndexRoute: AuthenticatedContractsIdIndexRoute,
  AuthenticatedInvoicesIdIndexRoute: AuthenticatedInvoicesIdIndexRoute,
  AuthenticatedLandlordsIdIndexRoute: AuthenticatedLandlordsIdIndexRoute,
  AuthenticatedMetersIdIndexRoute: AuthenticatedMetersIdIndexRoute,
  AuthenticatedPropertiesIdIndexRoute: AuthenticatedPropertiesIdIndexRoute,
  AuthenticatedTenantsIdIndexRoute: AuthenticatedTenantsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authAuthCallbackRoute: authAuthCallbackRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
